// Code generated by mdatagen. DO NOT EDIT.

package metadata_legacy

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverHostmetricsEmitV0SystemConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.hostmetrics.EmitV0SystemConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, semconv legacy attributes are disabled."),
	featuregate.WithRegisterReferenceURL("https://example.com"),
	featuregate.WithRegisterFromVersion("v0.145.0"),
)
