// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverHostmetricsEmitV1SystemConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.hostmetrics.EmitV1SystemConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, semconv stable attributes are enabled."),
	featuregate.WithRegisterReferenceURL("https://example.com"),
	featuregate.WithRegisterFromVersion("v0.145.0"),
)
