// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/connector/connectortest"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := connectortest.NewNopSettings(connectortest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPprofProfileDurationNanosecondsDataPoint(ts, 1, "period_type-val", "period_unit-val", "profile_id-val", "sample_type-val", "sample_unit-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPprofProfileFrameTypeSamplesDataPoint(ts, 1, "frame_type-val", "period_type-val", "period_unit-val", "profile_id-val", "sample_origin-val", "sample_type-val", "sample_unit-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPprofProfilePeriodDataPoint(ts, 1, "period_type-val", "period_unit-val", "profile_id-val", "sample_type-val", "sample_unit-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPprofProfileSampleCountDataPoint(ts, 1, "period_type-val", "period_unit-val", "profile_id-val", "sample_type-val", "sample_unit-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPprofProfileSampleValueSumDataPoint(ts, 1, "period_type-val", "period_unit-val", "profile_id-val", "sample_type-val", "sample_unit-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "pprof.profile.duration_nanoseconds":
					assert.False(t, validatedMetrics["pprof.profile.duration_nanoseconds"], "Found a duplicate in the metrics slice: pprof.profile.duration_nanoseconds")
					validatedMetrics["pprof.profile.duration_nanoseconds"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Wall duration of the profile observation window in nanoseconds.", mi.Description())
					assert.Equal(t, "ns", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					periodTypeAttrVal, ok := dp.Attributes().Get("period_type")
					assert.True(t, ok)
					assert.Equal(t, "period_type-val", periodTypeAttrVal.Str())
					periodUnitAttrVal, ok := dp.Attributes().Get("period_unit")
					assert.True(t, ok)
					assert.Equal(t, "period_unit-val", periodUnitAttrVal.Str())
					profileIDAttrVal, ok := dp.Attributes().Get("profile_id")
					assert.True(t, ok)
					assert.Equal(t, "profile_id-val", profileIDAttrVal.Str())
					sampleTypeAttrVal, ok := dp.Attributes().Get("sample_type")
					assert.True(t, ok)
					assert.Equal(t, "sample_type-val", sampleTypeAttrVal.Str())
					sampleUnitAttrVal, ok := dp.Attributes().Get("sample_unit")
					assert.True(t, ok)
					assert.Equal(t, "sample_unit-val", sampleUnitAttrVal.Str())
				case "pprof.profile.frame_type_samples":
					assert.False(t, validatedMetrics["pprof.profile.frame_type_samples"], "Found a duplicate in the metrics slice: pprof.profile.frame_type_samples")
					validatedMetrics["pprof.profile.frame_type_samples"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Count of stack samples attributed to each profile.frame.type on frames in the stack.", mi.Description())
					assert.Equal(t, "{sample}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					frameTypeAttrVal, ok := dp.Attributes().Get("frame_type")
					assert.True(t, ok)
					assert.Equal(t, "frame_type-val", frameTypeAttrVal.Str())
					periodTypeAttrVal, ok := dp.Attributes().Get("period_type")
					assert.True(t, ok)
					assert.Equal(t, "period_type-val", periodTypeAttrVal.Str())
					periodUnitAttrVal, ok := dp.Attributes().Get("period_unit")
					assert.True(t, ok)
					assert.Equal(t, "period_unit-val", periodUnitAttrVal.Str())
					profileIDAttrVal, ok := dp.Attributes().Get("profile_id")
					assert.True(t, ok)
					assert.Equal(t, "profile_id-val", profileIDAttrVal.Str())
					sampleOriginAttrVal, ok := dp.Attributes().Get("sample_origin")
					assert.True(t, ok)
					assert.Equal(t, "sample_origin-val", sampleOriginAttrVal.Str())
					sampleTypeAttrVal, ok := dp.Attributes().Get("sample_type")
					assert.True(t, ok)
					assert.Equal(t, "sample_type-val", sampleTypeAttrVal.Str())
					sampleUnitAttrVal, ok := dp.Attributes().Get("sample_unit")
					assert.True(t, ok)
					assert.Equal(t, "sample_unit-val", sampleUnitAttrVal.Str())
				case "pprof.profile.period":
					assert.False(t, validatedMetrics["pprof.profile.period"], "Found a duplicate in the metrics slice: pprof.profile.period")
					validatedMetrics["pprof.profile.period"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Profile sampling period in native units (often nanoseconds for CPU profiles).", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					periodTypeAttrVal, ok := dp.Attributes().Get("period_type")
					assert.True(t, ok)
					assert.Equal(t, "period_type-val", periodTypeAttrVal.Str())
					periodUnitAttrVal, ok := dp.Attributes().Get("period_unit")
					assert.True(t, ok)
					assert.Equal(t, "period_unit-val", periodUnitAttrVal.Str())
					profileIDAttrVal, ok := dp.Attributes().Get("profile_id")
					assert.True(t, ok)
					assert.Equal(t, "profile_id-val", profileIDAttrVal.Str())
					sampleTypeAttrVal, ok := dp.Attributes().Get("sample_type")
					assert.True(t, ok)
					assert.Equal(t, "sample_type-val", sampleTypeAttrVal.Str())
					sampleUnitAttrVal, ok := dp.Attributes().Get("sample_unit")
					assert.True(t, ok)
					assert.Equal(t, "sample_unit-val", sampleUnitAttrVal.Str())
				case "pprof.profile.sample_count":
					assert.False(t, validatedMetrics["pprof.profile.sample_count"], "Found a duplicate in the metrics slice: pprof.profile.sample_count")
					validatedMetrics["pprof.profile.sample_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of samples in the profile.", mi.Description())
					assert.Equal(t, "{sample}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					periodTypeAttrVal, ok := dp.Attributes().Get("period_type")
					assert.True(t, ok)
					assert.Equal(t, "period_type-val", periodTypeAttrVal.Str())
					periodUnitAttrVal, ok := dp.Attributes().Get("period_unit")
					assert.True(t, ok)
					assert.Equal(t, "period_unit-val", periodUnitAttrVal.Str())
					profileIDAttrVal, ok := dp.Attributes().Get("profile_id")
					assert.True(t, ok)
					assert.Equal(t, "profile_id-val", profileIDAttrVal.Str())
					sampleTypeAttrVal, ok := dp.Attributes().Get("sample_type")
					assert.True(t, ok)
					assert.Equal(t, "sample_type-val", sampleTypeAttrVal.Str())
					sampleUnitAttrVal, ok := dp.Attributes().Get("sample_unit")
					assert.True(t, ok)
					assert.Equal(t, "sample_unit-val", sampleUnitAttrVal.Str())
				case "pprof.profile.sample_value_sum":
					assert.False(t, validatedMetrics["pprof.profile.sample_value_sum"], "Found a duplicate in the metrics slice: pprof.profile.sample_value_sum")
					validatedMetrics["pprof.profile.sample_value_sum"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Sum of sample Values() across all samples in the profile (e.g. total CPU ns, allocated bytes).", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					periodTypeAttrVal, ok := dp.Attributes().Get("period_type")
					assert.True(t, ok)
					assert.Equal(t, "period_type-val", periodTypeAttrVal.Str())
					periodUnitAttrVal, ok := dp.Attributes().Get("period_unit")
					assert.True(t, ok)
					assert.Equal(t, "period_unit-val", periodUnitAttrVal.Str())
					profileIDAttrVal, ok := dp.Attributes().Get("profile_id")
					assert.True(t, ok)
					assert.Equal(t, "profile_id-val", profileIDAttrVal.Str())
					sampleTypeAttrVal, ok := dp.Attributes().Get("sample_type")
					assert.True(t, ok)
					assert.Equal(t, "sample_type-val", sampleTypeAttrVal.Str())
					sampleUnitAttrVal, ok := dp.Attributes().Get("sample_unit")
					assert.True(t, ok)
					assert.Equal(t, "sample_unit-val", sampleUnitAttrVal.Str())
				}
			}
		})
	}
}
