// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("pprofmetrics")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/connector/pprofmetricsconnector"
)

const (
	ProfilesToMetricsStability = component.StabilityLevelDevelopment
)
