// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/connector"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
)

var MetricsInfo = metricsInfo{
	PprofProfileDurationNanoseconds: metricInfo{
		Name: "pprof.profile.duration_nanoseconds",
	},
	PprofProfileFrameTypeSamples: metricInfo{
		Name: "pprof.profile.frame_type_samples",
	},
	PprofProfilePeriod: metricInfo{
		Name: "pprof.profile.period",
	},
	PprofProfileSampleCount: metricInfo{
		Name: "pprof.profile.sample_count",
	},
	PprofProfileSampleValueSum: metricInfo{
		Name: "pprof.profile.sample_value_sum",
	},
}

type metricsInfo struct {
	PprofProfileDurationNanoseconds metricInfo
	PprofProfileFrameTypeSamples    metricInfo
	PprofProfilePeriod              metricInfo
	PprofProfileSampleCount         metricInfo
	PprofProfileSampleValueSum      metricInfo
}

type metricInfo struct {
	Name string
}

type metricPprofProfileDurationNanoseconds struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pprof.profile.duration_nanoseconds metric with initial data.
func (m *metricPprofProfileDurationNanoseconds) init() {
	m.data.SetName("pprof.profile.duration_nanoseconds")
	m.data.SetDescription("Wall duration of the profile observation window in nanoseconds.")
	m.data.SetUnit("ns")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPprofProfileDurationNanoseconds) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("period_type", periodTypeAttributeValue)
	dp.Attributes().PutStr("period_unit", periodUnitAttributeValue)
	dp.Attributes().PutStr("profile_id", profileIDAttributeValue)
	dp.Attributes().PutStr("sample_type", sampleTypeAttributeValue)
	dp.Attributes().PutStr("sample_unit", sampleUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPprofProfileDurationNanoseconds) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPprofProfileDurationNanoseconds) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPprofProfileDurationNanoseconds(cfg MetricConfig) metricPprofProfileDurationNanoseconds {
	m := metricPprofProfileDurationNanoseconds{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPprofProfileFrameTypeSamples struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pprof.profile.frame_type_samples metric with initial data.
func (m *metricPprofProfileFrameTypeSamples) init() {
	m.data.SetName("pprof.profile.frame_type_samples")
	m.data.SetDescription("Count of stack samples attributed to each profile.frame.type on frames in the stack.")
	m.data.SetUnit("{sample}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPprofProfileFrameTypeSamples) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, frameTypeAttributeValue string, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleOriginAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("frame_type", frameTypeAttributeValue)
	dp.Attributes().PutStr("period_type", periodTypeAttributeValue)
	dp.Attributes().PutStr("period_unit", periodUnitAttributeValue)
	dp.Attributes().PutStr("profile_id", profileIDAttributeValue)
	dp.Attributes().PutStr("sample_origin", sampleOriginAttributeValue)
	dp.Attributes().PutStr("sample_type", sampleTypeAttributeValue)
	dp.Attributes().PutStr("sample_unit", sampleUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPprofProfileFrameTypeSamples) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPprofProfileFrameTypeSamples) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPprofProfileFrameTypeSamples(cfg MetricConfig) metricPprofProfileFrameTypeSamples {
	m := metricPprofProfileFrameTypeSamples{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPprofProfilePeriod struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pprof.profile.period metric with initial data.
func (m *metricPprofProfilePeriod) init() {
	m.data.SetName("pprof.profile.period")
	m.data.SetDescription("Profile sampling period in native units (often nanoseconds for CPU profiles).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPprofProfilePeriod) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("period_type", periodTypeAttributeValue)
	dp.Attributes().PutStr("period_unit", periodUnitAttributeValue)
	dp.Attributes().PutStr("profile_id", profileIDAttributeValue)
	dp.Attributes().PutStr("sample_type", sampleTypeAttributeValue)
	dp.Attributes().PutStr("sample_unit", sampleUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPprofProfilePeriod) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPprofProfilePeriod) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPprofProfilePeriod(cfg MetricConfig) metricPprofProfilePeriod {
	m := metricPprofProfilePeriod{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPprofProfileSampleCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pprof.profile.sample_count metric with initial data.
func (m *metricPprofProfileSampleCount) init() {
	m.data.SetName("pprof.profile.sample_count")
	m.data.SetDescription("Number of samples in the profile.")
	m.data.SetUnit("{sample}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPprofProfileSampleCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("period_type", periodTypeAttributeValue)
	dp.Attributes().PutStr("period_unit", periodUnitAttributeValue)
	dp.Attributes().PutStr("profile_id", profileIDAttributeValue)
	dp.Attributes().PutStr("sample_type", sampleTypeAttributeValue)
	dp.Attributes().PutStr("sample_unit", sampleUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPprofProfileSampleCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPprofProfileSampleCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPprofProfileSampleCount(cfg MetricConfig) metricPprofProfileSampleCount {
	m := metricPprofProfileSampleCount{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPprofProfileSampleValueSum struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pprof.profile.sample_value_sum metric with initial data.
func (m *metricPprofProfileSampleValueSum) init() {
	m.data.SetName("pprof.profile.sample_value_sum")
	m.data.SetDescription("Sum of sample Values() across all samples in the profile (e.g. total CPU ns, allocated bytes).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPprofProfileSampleValueSum) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("period_type", periodTypeAttributeValue)
	dp.Attributes().PutStr("period_unit", periodUnitAttributeValue)
	dp.Attributes().PutStr("profile_id", profileIDAttributeValue)
	dp.Attributes().PutStr("sample_type", sampleTypeAttributeValue)
	dp.Attributes().PutStr("sample_unit", sampleUnitAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPprofProfileSampleValueSum) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPprofProfileSampleValueSum) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPprofProfileSampleValueSum(cfg MetricConfig) metricPprofProfileSampleValueSum {
	m := metricPprofProfileSampleValueSum{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                MetricsBuilderConfig // config of the metrics builder.
	startTime                             pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                       int                  // maximum observed number of metrics per resource.
	metricsBuffer                         pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                             component.BuildInfo  // contains version information.
	metricPprofProfileDurationNanoseconds metricPprofProfileDurationNanoseconds
	metricPprofProfileFrameTypeSamples    metricPprofProfileFrameTypeSamples
	metricPprofProfilePeriod              metricPprofProfilePeriod
	metricPprofProfileSampleCount         metricPprofProfileSampleCount
	metricPprofProfileSampleValueSum      metricPprofProfileSampleValueSum
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings connector.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                mbc,
		startTime:                             pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                         pmetric.NewMetrics(),
		buildInfo:                             settings.BuildInfo,
		metricPprofProfileDurationNanoseconds: newMetricPprofProfileDurationNanoseconds(mbc.Metrics.PprofProfileDurationNanoseconds),
		metricPprofProfileFrameTypeSamples:    newMetricPprofProfileFrameTypeSamples(mbc.Metrics.PprofProfileFrameTypeSamples),
		metricPprofProfilePeriod:              newMetricPprofProfilePeriod(mbc.Metrics.PprofProfilePeriod),
		metricPprofProfileSampleCount:         newMetricPprofProfileSampleCount(mbc.Metrics.PprofProfileSampleCount),
		metricPprofProfileSampleValueSum:      newMetricPprofProfileSampleValueSum(mbc.Metrics.PprofProfileSampleValueSum),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricPprofProfileDurationNanoseconds.emit(ils.Metrics())
	mb.metricPprofProfileFrameTypeSamples.emit(ils.Metrics())
	mb.metricPprofProfilePeriod.emit(ils.Metrics())
	mb.metricPprofProfileSampleCount.emit(ils.Metrics())
	mb.metricPprofProfileSampleValueSum.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordPprofProfileDurationNanosecondsDataPoint adds a data point to pprof.profile.duration_nanoseconds metric.
func (mb *MetricsBuilder) RecordPprofProfileDurationNanosecondsDataPoint(ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	mb.metricPprofProfileDurationNanoseconds.recordDataPoint(mb.startTime, ts, val, periodTypeAttributeValue, periodUnitAttributeValue, profileIDAttributeValue, sampleTypeAttributeValue, sampleUnitAttributeValue)
}

// RecordPprofProfileFrameTypeSamplesDataPoint adds a data point to pprof.profile.frame_type_samples metric.
func (mb *MetricsBuilder) RecordPprofProfileFrameTypeSamplesDataPoint(ts pcommon.Timestamp, val int64, frameTypeAttributeValue string, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleOriginAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	mb.metricPprofProfileFrameTypeSamples.recordDataPoint(mb.startTime, ts, val, frameTypeAttributeValue, periodTypeAttributeValue, periodUnitAttributeValue, profileIDAttributeValue, sampleOriginAttributeValue, sampleTypeAttributeValue, sampleUnitAttributeValue)
}

// RecordPprofProfilePeriodDataPoint adds a data point to pprof.profile.period metric.
func (mb *MetricsBuilder) RecordPprofProfilePeriodDataPoint(ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	mb.metricPprofProfilePeriod.recordDataPoint(mb.startTime, ts, val, periodTypeAttributeValue, periodUnitAttributeValue, profileIDAttributeValue, sampleTypeAttributeValue, sampleUnitAttributeValue)
}

// RecordPprofProfileSampleCountDataPoint adds a data point to pprof.profile.sample_count metric.
func (mb *MetricsBuilder) RecordPprofProfileSampleCountDataPoint(ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	mb.metricPprofProfileSampleCount.recordDataPoint(mb.startTime, ts, val, periodTypeAttributeValue, periodUnitAttributeValue, profileIDAttributeValue, sampleTypeAttributeValue, sampleUnitAttributeValue)
}

// RecordPprofProfileSampleValueSumDataPoint adds a data point to pprof.profile.sample_value_sum metric.
func (mb *MetricsBuilder) RecordPprofProfileSampleValueSumDataPoint(ts pcommon.Timestamp, val int64, periodTypeAttributeValue string, periodUnitAttributeValue string, profileIDAttributeValue string, sampleTypeAttributeValue string, sampleUnitAttributeValue string) {
	mb.metricPprofProfileSampleValueSum.recordDataPoint(mb.startTime, ts, val, periodTypeAttributeValue, periodUnitAttributeValue, profileIDAttributeValue, sampleTypeAttributeValue, sampleUnitAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
