// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for pprofmetrics metrics.
type MetricsConfig struct {
	PprofProfileDurationNanoseconds MetricConfig `mapstructure:"pprof.profile.duration_nanoseconds"`
	PprofProfileFrameTypeSamples    MetricConfig `mapstructure:"pprof.profile.frame_type_samples"`
	PprofProfilePeriod              MetricConfig `mapstructure:"pprof.profile.period"`
	PprofProfileSampleCount         MetricConfig `mapstructure:"pprof.profile.sample_count"`
	PprofProfileSampleValueSum      MetricConfig `mapstructure:"pprof.profile.sample_value_sum"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PprofProfileDurationNanoseconds: MetricConfig{
			Enabled: true,
		},
		PprofProfileFrameTypeSamples: MetricConfig{
			Enabled: true,
		},
		PprofProfilePeriod: MetricConfig{
			Enabled: true,
		},
		PprofProfileSampleCount: MetricConfig{
			Enabled: true,
		},
		PprofProfileSampleValueSum: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for pprofmetrics metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
