extensions:
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        path: "/health/status"
      config:
        enabled: true
        path: "/health/config"
  # opamp:
  #   server:
  #     ws:
  #       endpoint: ws://127.0.0.1:4000/v1/opamp
  #       tls:
  #         insecure: true

receivers:
  otlp/manual:
    protocols:
      grpc:
        endpoint: localhost:4319
      http:
        endpoint: localhost:4320
  xcreator:

processors:
  resource/manual:
    attributes:
      - key: manual_insert
        value: true
        action: insert
  remotetap:

exporters:
  debug:
    verbosity: detailed

service:
  extensions:
    - healthcheckv2
    # - opamp
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
    logs:
      level: debug
      # processors:
      #   - batch:
      #       exporter:
      #         otlp:
      #           protocol: http/protobuf
      #           endpoint: http://localhost:4325
  pipelines:
    metrics:
      receivers:
        - xcreator
        - otlp/manual
      processors:
        - resource/manual
        - remotetap
      exporters:
        - debug
