// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("xfilterprocessor")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/xfilterprocessor"
)

const (
	ProfilesStability = component.StabilityLevelDevelopment
)
